### ISSUE TITLE
Error while executing "build-transaction-bundle.py"

### ISSUE THREAD

**Issue by florisa** [juliangruendner/pj7-data-extraction#5] opened 2022-12-14 11:35 UTC
mii-data-extraction_1  | Finished pseudonymisation of: extracted_resources/cond.json
mii-data-extraction_1  | Finished pseudonymising data
mii-data-extraction_1  | Begin creation of extraction transfer bundle...
mii-data-extraction_1  | Traceback (most recent call last):
mii-data-extraction_1  |   File "/opt/data-extraction/build-transaction-bundle.py", line 82, in <module>
mii-data-extraction_1  |     existing_doc_ref_id = get_existing_doc_ref(project_ident)
mii-data-extraction_1  |   File "/opt/data-extraction/build-transaction-bundle.py", line 77, in get_existing_doc_ref
mii-data-extraction_1  |     return resp_json["entry"][0]["resource"]["id"]
mii-data-extraction_1  | IndexError: list index out of range
mii-data-extraction_1  | Finished creation of extraction transfer bundle...
mii-data-extraction_1  | Goodbye - have a nice day
mii-projectathon_mii-data-extraction_1 exited with code 0

**Comment by florisa** [comment] 2022-12-14 11:37
We are using blaze v.016, could be a problem with this version?

**Comment by juliangruendner** [comment] 2022-12-14 11:40
@florisa  - duplicate of issue https://github.com/juliangruendner/pj7-data-extraction/issues/2
please pull the newest version and try again - if it still persists let me know and i will have another look

**Closed as completed by juliangruendner** 2022-12-14 11:40 UTC

**Comment by florisa** [comment] 2022-12-14 12:12
It works now! Thanks
